# Generated by Django 5.0.4 on 2024-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_customuser_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
